In [2]:
import sys
import os
from retinaface import RetinaFace
import cv2
import time
from datetime import timedelta

print("Python version")
print(sys.version)
print("Version info.")
print(sys.version_info)
print("Current Path: " + os.getcwd())

Python version
3.10.0 | packaged by conda-forge | (default, Nov 10 2021, 13:20:59) [MSC v.1916 64 bit (AMD64)]
Version info.
sys.version_info(major=3, minor=10, micro=0, releaselevel='final', serial=0)
Current Path: c:\Users\simplelab-kyochul\Documents\Simple_Lab\back_front_classifier


In [3]:
import tensorflow as tf

if tf.test.is_gpu_available():
    print("GPU is available")
else:
    print("GPU is NOT available")

GPU is available


In [5]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [16]:
for idx, img in enumerate(os.listdir(os.path.join(os.getcwd(), "example_pics"))):
    img_path = os.path.join(os.getcwd(), f'example_pics\{img}')
    if img_path[img_path.rfind('.')+1:] == 'png':
        obj = RetinaFace.detect_faces(img_path)
        if type(obj) == dict:
            print(f'{img}: {obj}' + '|||' + f'len(obj): {len(obj)}')
    print()



2.png: {'face_1': {'score': 0.9994255304336548, 'facial_area': [734, 177, 827, 278], 'landmarks': {'right_eye': [765.96136, 218.37329], 'left_eye': [805.85803, 226.90715], 'nose': [781.75995, 247.61446], 'mouth_right': [759.7005, 252.14607], 'mouth_left': [789.93634, 259.15524]}}}|||len(obj): 1


4.png: {'face_1': {'score': 0.9995377659797668, 'facial_area': [623, 133, 716, 238], 'landmarks': {'right_eye': [650.3352, 183.90204], 'left_eye': [693.8385, 184.68657], 'nose': [672.54144, 210.88965], 'mouth_right': [652.58734, 214.14919], 'mouth_left': [688.0053, 215.06595]}}}|||len(obj): 1

5.png: {'face_1': {'score': 0.9973743557929993, 'facial_area': [841, 158, 908, 238], 'landmarks': {'right_eye': [859.9083, 188.20197], 'left_eye': [891.9024, 186.12212], 'nose': [877.81335, 207.16994], 'mouth_right': [865.891, 221.7853], 'mouth_left': [889.32916, 220.24525]}}}|||len(obj): 1


7.png: {'face_1': {'score': 0.9994286298751831, 'facial_area': [711, 340, 774, 420], 'landmarks': {'right_eye':

# Code for Testing

In [24]:
tic = time.time()
video_num, front_vid_num, back_vid_num = 0, 0, 0
for idx, vid in enumerate(os.listdir(os.path.join(os.getcwd(), "example_vids"))):
    vid_path = os.path.join(os.getcwd(), f'example_vids\{vid}')
    
    # check if the file is mov file or not
    if not vid_path[vid_path.rfind('.') + 1:] == 'MOV':
        print(f'{vid} is not a video.')
        continue
    
    cap = cv2.VideoCapture(vid_path)
    video_num += 1
    frame_num, front_poss, back_poss = 0, 0, 0
    print(f'Current Video: {vid}')
    
    while True:
        ret, frame = cap.read()
        
        if not ret:
            break
        
        if frame_num % 30 == 0:
            # print(f'Detect at {frame_num / 30} second')
            obj = RetinaFace.detect_faces(frame)
        
            if type(obj) == dict:
                front_poss += 1
            else:
                back_poss += 1
        
        frame_num += 1
        
        
    print(f'front_poss: {front_poss}')
    print(f'back_poss: {back_poss}')
    if front_poss > back_poss:
        print(f'{vid} is a front view video.')
        front_vid_num += 1
    else: 
        print(f'{vid} is a back view video.')
        back_vid_num += 1
    print()

print(time)
elapsed = time.time() - tic
formatted_elapsed = str(timedelta(seconds=elapsed))
print(f'Video_num: {video_num}')
print(f'Elapsed Time(%hh:%mm:%ss.xxx): {formatted_elapsed}')
print(f'Result:')
print(f'front_vid_num: {front_vid_num}')
print(f'back_vid_num: {back_vid_num}')

Current Video: 20200901_120245.MOV
Detect at 0.0 second
[[[126 172 202]
  [124 169 199]
  [120 166 196]
  ...
  [ 81 132 159]
  [ 82 133 160]
  [ 82 133 160]]

 [[126 172 202]
  [124 169 199]
  [120 166 196]
  ...
  [ 81 132 159]
  [ 82 133 160]
  [ 82 133 160]]

 [[126 172 202]
  [124 169 199]
  [120 166 196]
  ...
  [ 82 133 160]
  [ 83 134 161]
  [ 83 134 161]]

 ...

 [[ 63  71  86]
  [ 81  89 105]
  [ 81  89 105]
  ...
  [ 15  50  85]
  [  0  17  53]
  [  0  16  51]]

 [[ 79  83  94]
  [ 97 102 113]
  [ 97 102 113]
  ...
  [ 18  46  73]
  [  0   7  34]
  [  0   0  19]]

 [[108 112 123]
  [115 119 130]
  [ 91  96 107]
  ...
  [ 30  58  85]
  [  0  28  55]
  [  0   0  19]]]
Detect at 1.0 second
[[[126 172 202]
  [124 169 199]
  [120 166 196]
  ...
  [ 82 133 160]
  [ 82 133 160]
  [ 82 133 160]]

 [[126 172 202]
  [124 169 199]
  [120 166 196]
  ...
  [ 82 133 160]
  [ 82 133 160]
  [ 82 133 160]]

 [[126 172 202]
  [124 169 199]
  [120 166 196]
  ...
  [ 82 133 160]
  [ 83 134 161]

# Actual Code

In [6]:
front_dir_path = r'C:\Users\simplelab-kyochul\Documents\front_view'
back_dir_path = r'C:\Users\simplelab-kyochul\Documents\back_view'

## Front_View Classifier

In [7]:
tic = time.time()
remove_list = []
for action_cam in os.listdir(front_dir_path):
    new_path = os.path.join(front_dir_path, action_cam)
    if not os.path.isdir(new_path):
        print(f'{action_cam} is not a folder.')
        continue
    for action in os.listdir(new_path):
        new_path1 = os.path.join(new_path, action)
        if not os.path.isdir(new_path1):
            print(f'{action} is not a folder')
            continue
        
        for idx, vid in enumerate(os.listdir(new_path1)):
            vid_path = os.path.join(new_path1, vid)
    
            # check if the file is mov file or not
            if not vid_path[vid_path.rfind('.') + 1:] == 'MOV':
                print(f'{vid} is not a video.')
                continue
            
            cap = cv2.VideoCapture(vid_path)
            
            frame_num, front_frame, back_frame = 0, 0, 0
            print(f'Current Video: {vid}')
            
            while True:
                ret, frame = cap.read()
                
                if not ret:
                    break
                
                if frame_num % 30 == 0:
                    # print(f'Detect at {frame_num / 30} second')
                    obj = RetinaFace.detect_faces(frame)
                
                    if type(obj) == dict:
                        front_frame += 1
                    else:
                        back_frame += 1
                
                frame_num += 1
                
                
            if not front_frame > back_frame:
                remove_list.append(vid_path)

for vid in remove_list:
    os.remove(vid)

print(time)
elapsed = time.time() - tic
formatted_elapsed = str(timedelta(seconds=elapsed))
print(f'Video_num: {video_num}')
print(f'Elapsed Time(%hh:%mm:%ss.xxx): {formatted_elapsed}')


Current Video: 20200901_120603.MOV
Current Video: 20200901_120617.MOV
Current Video: 20200901_120631_01.MOV
Current Video: 20200901_120642.MOV
Current Video: 20200901_122306.MOV
Current Video: 20200901_122323.MOV
Current Video: 20200901_122332.MOV
Current Video: 20200901_122340.MOV
Current Video: 20200901_133441.MOV
Current Video: 20200901_133452.MOV
Current Video: 20200901_133503.MOV
Current Video: 20200901_133513.MOV
Current Video: 20200901_133522_01.MOV
Current Video: 20200901_143308.MOV
Current Video: 20200901_143317.MOV
Current Video: 20200901_144435.MOV
Current Video: 20200901_150228.MOV
Current Video: 20200901_150255.MOV
Current Video: 20200901_152306.MOV
Current Video: 20200901_152314.MOV
Current Video: 20200901_160111.MOV
Current Video: 20200901_160201.MOV
Current Video: 20200901_160213.MOV
Current Video: 20200901_160222.MOV
Current Video: 20200901_160231.MOV
Current Video: 20200901_163359.MOV
Current Video: 20200901_163412.MOV
Current Video: 20200901_163426.MOV
Current Video:

KeyboardInterrupt: 

## Back_View Classifier

In [ ]:
tic = time.time()
video_num, front_vid_num, back_vid_num = 0, 0, 0
for idx, vid in enumerate(os.listdir(os.path.join(os.getcwd(), "example_vids"))):
    vid_path = os.path.join(os.getcwd(), f'example_vids\{vid}')
    
    # check if the file is mov file or not
    if not vid_path[vid_path.rfind('.') + 1:] == 'MOV':
        print(f'{vid} is not a video.')
        continue
    
    cap = cv2.VideoCapture(vid_path)
    video_num += 1
    frame_num, front_poss, back_poss = 0, 0, 0
    print(f'Current Video: {vid}')
    
    while True:
        ret, frame = cap.read()
        
        if not ret:
            break
        
        if frame_num % 30 == 0:
            # print(f'Detect at {frame_num / 30} second')
            obj = RetinaFace.detect_faces(frame)
        
            if type(obj) == dict:
                front_poss += 1
            else:
                back_poss += 1
        
        frame_num += 1
        
        
    print(f'front_poss: {front_poss}')
    print(f'back_poss: {back_poss}')
    if front_poss > back_poss:
        print(f'{vid} is a front view video.')
        front_vid_num += 1
    else: 
        print(f'{vid} is a back view video.')
        back_vid_num += 1
    print()

print(time)
elapsed = time.time() - tic
formatted_elapsed = str(timedelta(seconds=elapsed))
print(f'Video_num: {video_num}')
print(f'Elapsed Time(%hh:%mm:%ss.xxx): {formatted_elapsed}')
print(f'Result:')
print(f'front_vid_num: {front_vid_num}')
print(f'back_vid_num: {back_vid_num}')